#!/usr/bin/env Rscript

# Fixed minimal report generation V2
# Corrected data structure access

library(tidyverse)
library(here)
library(cli)

#' Generate minimal experimental summary report
generate_minimal_summary <- function(experiment_name, res.l.all, dds, coldata) {
  
  # Create basic summary data
  summary_data <- list(
    experiment_name = experiment_name,
    n_samples = ncol(dds),
    n_transcripts = nrow(dds),
    n_comparisons = length(res.l.all),
    analysis_date = Sys.Date(),
    comparison_summary = res.l.all %>%
      imap_dfr(function(comp_data, comp_name) {
        tibble(
          comparison = comp_name,
          total_genes = nrow(comp_data$all),
          sig_genes = nrow(comp_data$sig),
          de_genes = nrow(comp_data$DE)
        )
      })
  )
  
  # Create CSS as separate string to avoid glue issues
  css_style <- '
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #333; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; }
  '
  
  # Create table rows
  table_rows <- summary_data$comparison_summary %>%
    pmap_chr(function(comparison, total_genes, sig_genes, de_genes) {
      paste0("<tr><td>", comparison, "</td><td>", total_genes, "</td><td>", sig_genes, "</td><td>", de_genes, "</td></tr>")
    }) %>%
    paste(collapse = "\n        ")
  
  # Create links
  comparison_links <- names(res.l.all) %>%
    map_chr(function(comp_name) {
      paste0('<li><a href="', comp_name, '_minimal.html">', comp_name, '</a></li>')
    }) %>%
    paste(collapse = "\n        ")
  
  # Build HTML content without glue interpolation in CSS
  html_content <- paste0(
    '<!DOCTYPE html>
<html>
<head>
  <title>RNA-seq Analysis: ', summary_data$experiment_name, '</title>
  <style>', css_style, '</style>
</head>
<body>
  <h1>RNA-seq Analysis: ', summary_data$experiment_name, '</h1>
  <p><strong>Analysis Date:</strong> ', summary_data$analysis_date, '</p>
  
  <h2>Experiment Overview</h2>
  <ul>
    <li><strong>Samples:</strong> ', summary_data$n_samples, '</li>
    <li><strong>Transcripts:</strong> ', scales::comma(summary_data$n_transcripts), '</li>
    <li><strong>Comparisons:</strong> ', summary_data$n_comparisons, '</li>
  </ul>
  
  <h2>Comparison Summary</h2>
  <table>
    <tr>
      <th>Comparison</th>
      <th>Total Genes</th>
      <th>Significant</th>
      <th>Differential</th>
    </tr>
    ', table_rows, '
  </table>
  
  <h2>Individual Reports</h2>
  <ul>
    ', comparison_links, '
  </ul>
  
  <p><em>Generated by Yildiz Lab RNA-seq Pipeline</em></p>
</body>
</html>')
  
  # Save HTML file to outputs/R directory
  reports_dir <- here("experiments", experiment_name, "outputs", "R")
  if (!dir.exists(reports_dir)) {
    dir.create(reports_dir, recursive = TRUE)
  }
  
  output_file <- file.path(reports_dir, paste0(experiment_name, "_minimal_summary.html"))
  writeLines(html_content, output_file)
  
  cli_inform("Generated minimal summary: {basename(output_file)}")
  return(output_file)
}

#' Generate minimal comparison report - FIXED data structure access
generate_minimal_comparison <- function(comparison_name, comparison_data, experiment_name) {
  
  # FIXED: Access data directly, not through $results
  # comparison_data should have $all, $sig, $DE directly
  results_all <- comparison_data$all
  results_sig <- comparison_data$sig  
  results_de <- comparison_data$DE
  contrast <- comparison_data$contrast
  
  # Debug info
  cli_inform("Processing {comparison_name}:")
  cli_inform("  - All results: {nrow(results_all)} genes")
  cli_inform("  - Significant: {nrow(results_sig)} genes") 
  cli_inform("  - Differential: {nrow(results_de)} genes")
  
  # CSS style
  css_style <- '
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #333; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; }
    .number { text-align: right; }
  '
  
  # Create top genes table - FIXED to use results_de instead of results$DE
  if (nrow(results_de) > 0) {
    top_genes <- results_de %>%
      arrange(padj) %>%
      slice_head(n = 10) %>%
      select(Label, any_of('Product'), log2FoldChange, padj) %>%
      mutate(
        log2FoldChange = round(log2FoldChange, 3),
        padj = scales::scientific(padj, digits = 2)
      )
    
    genes_table <- top_genes %>%
      pmap_chr(function(...) {
        row_data <- list(...)
        product <- if ('Product' %in% names(row_data)) row_data[['Product']] else 'N/A'
        if (is.na(product)) product <- 'N/A'
        
        paste0('<tr><td>', row_data[['Label']], '</td><td>', product, 
               '</td><td class="number">', row_data[['log2FoldChange']], 
               '</td><td class="number">', row_data[['padj']], '</td></tr>')
      }) %>%
      paste(collapse = "\n        ")
  } else {
    genes_table <- '<tr><td colspan="4">No differentially expressed genes found</td></tr>'
  }
  
  # Build HTML content - FIXED to use direct variable references
  html_content <- paste0(
    '<!DOCTYPE html>
<html>
<head>
  <title>Differential Expression: ', comparison_name, '</title>
  <style>', css_style, '</style>
</head>
<body>
  <h1>Differential Expression: ', comparison_name, '</h1>
  <p><strong>Comparison:</strong> ', contrast[2], ' vs ', contrast[3], '</p>
  
  <h2>Summary</h2>
  <ul>
    <li><strong>Total genes:</strong> ', scales::comma(nrow(results_all)), '</li>
    <li><strong>Significant (padj ≤ 0.05):</strong> ', nrow(results_sig), '</li>
    <li><strong>Differentially expressed:</strong> ', nrow(results_de), '</li>
  </ul>
  
  <h2>Top 10 Differentially Expressed Genes</h2>
  <table>
    <tr>
      <th>Gene</th>
      <th>Product</th>
      <th>log2FC</th>
      <th>padj</th>
    </tr>
    ', genes_table, '
  </table>
  
  <p><a href="', experiment_name, '_minimal_summary.html">← Back to Summary</a></p>
  <p><em>Generated by Yildiz Lab RNA-seq Pipeline</em></p>
</body>
</html>')
  
  # Save HTML file to outputs/R directory
  reports_dir <- here("experiments", experiment_name, "outputs", "R")
  output_file <- file.path(reports_dir, paste0(comparison_name, "_minimal.html"))
  writeLines(html_content, output_file)
  
  cli_inform("Generated minimal comparison: {basename(output_file)}")
  return(output_file)
}

#' Generate all minimal reports - FIXED data structure handling
generate_minimal_reports <- function(experiment_name, res.l.all, dds, coldata, contrast_list) {
  
  cli_inform("Generating minimal reports for {experiment_name}...")
  
  # Source comparison name formatting function
  source(here("functions/differential_expression.R"))
  
  # Debug: Check structure of first comparison
  first_comp <- res.l.all[[1]]
  cli_inform("Debug - First comparison structure:")
  cli_inform("  Names: {paste(names(first_comp), collapse = ', ')}")
  if ('all' %in% names(first_comp)) {
    cli_inform("  All results: {nrow(first_comp$all)} genes")
  }
  
  # Add contrast info to results - FIXED to not wrap in $results
  res.l.all.with_contrast <- res.l.all %>%
    imap(function(comp_data, comp_name) {
      # Find matching contrast
      contrast_idx <- which(sapply(contrast_list, function(c) {
        format_comparison_name(c) == comp_name
      }))
      
      if (length(contrast_idx) > 0) {
        comp_data$contrast <- contrast_list[[contrast_idx[1]]]
      } else {
        # Fallback - try to parse from name
        parts <- str_split(comp_name, "_v_")[[1]]
        if (length(parts) == 2) {
          comp_data$contrast <- c("group", parts[1], parts[2])
        } else {
          comp_data$contrast <- c("unknown", "treatment", "control")
        }
      }
      
      # Return the comparison data with contrast info added
      comp_data
    })
  
  # Generate summary report
  summary_file <- generate_minimal_summary(experiment_name, res.l.all, dds, coldata)
  
  # Generate individual comparison reports - FIXED error handling
  comparison_files <- res.l.all.with_contrast %>%
    imap(function(comp_data, comp_name) {
      tryCatch({
        generate_minimal_comparison(comp_name, comp_data, experiment_name)
      }, error = function(e) {
        cli_warn("Failed to generate report for {comp_name}: {e$message}")
        cli_warn("Comparison data structure: {paste(names(comp_data), collapse = ', ')}")
        return(NULL)
      })
    }) %>%
    keep(~ !is.null(.x))  # Remove NULL entries from failures
  
  cli_inform("Generated {length(comparison_files) + 1} minimal report files")
  cli_inform("Open summary: experiments/{experiment_name}/outputs/R/{experiment_name}_minimal_summary.html")
  
  return(c(summary = summary_file, comparison_files))
}

#' Debug function to check data structure
debug_comparison_structure <- function(res.l.all) {
  cli_rule("Debugging Comparison Data Structure")
  
  cli_inform("Total comparisons: {length(res.l.all)}")
  cli_inform("Comparison names: {paste(names(res.l.all), collapse = ', ')}")
  
  # Check first comparison in detail
  if (length(res.l.all) > 0) {
    first_name <- names(res.l.all)[1]
    first_comp <- res.l.all[[1]]
    
    cli_inform("First comparison: {first_name}")
    cli_inform("Structure: {paste(names(first_comp), collapse = ', ')}")
    
    if ('all' %in% names(first_comp)) {
      cli_inform("'all' contains {nrow(first_comp$all)} rows")
      cli_inform("'all' columns: {paste(names(first_comp$all), collapse = ', ')}")
    }
    
    if ('sig' %in% names(first_comp)) {
      cli_inform("'sig' contains {nrow(first_comp$sig)} rows")
    }
    
    if ('DE' %in% names(first_comp)) {
      cli_inform("'DE' contains {nrow(first_comp$DE)} rows")
    }
  }
  
  cli_rule()
}